const base = () => import.meta.env.BASE_URL;
const p = (path) => `${base()}${path}`;

export const LEGAL =
  'Diese Information gibt einen Überblick. Maßgeblich sind die Versicherungsbedingungen und das individuelle Angebot. Stand: Okt. 2026.';

export const CTA =
  'Ihr individuelles Angebot nach 30 Min. Risikoaufnahme — bindende Euro-Beträge nur im späteren Angebots-PDF.';

export const sections = [
  { id: 'hero', label: 'Start' },
  { id: 'lage', label: 'Lage' },
  { id: 'risiko', label: 'Risiko' },
  { id: 'haftung', label: 'Haftung' },
  { id: 'bauwerk', label: 'Bauwerk' },
  { id: 'maschinen', label: 'Maschinen' },
  { id: 'inhalt', label: 'Inhalt' },
  { id: 'recht', label: 'Recht' },
  { id: 'liquiditaet', label: 'Liquidität' },
  { id: 'menschen', label: 'Menschen' },
  { id: 'warum', label: 'Warum ERGO' },
  { id: 'beitrag', label: 'Beitrag' },
  { id: 'paket', label: 'Paket' },
  { id: 'naechste', label: 'Nächste' },
  { id: 'schluss', label: 'Abschluss' },
];

/** Package builder items — no euro amounts on core products */
export const PACKAGE_ITEMS = [
  { id: 'haftpflicht', name: 'Betriebs-Haftpflicht', tier: 'must', note: 'Bauhauptgewerbe-Bedingungswerk' },
  { id: 'bauleistung', name: 'Bauleistungsversicherung', tier: 'must', note: 'Objekt / Rahmen — ABU ggf. prüfen' },
  { id: 'maschinen', name: 'Maschinen- und Kaskoversicherung', tier: 'must', note: 'Fahrbare Geräte' },
  { id: 'inhalt', name: 'Geschäftsinhaltsversicherung', tier: 'must', note: '+ Bauhandwerker-Paket' },
  { id: 'unfall', name: 'Gruppen-Unfallversicherung', tier: 'recommended', note: 'Ergänzung zur BG BAU' },
  { id: 'kaution', name: 'Kautionsversicherung', tier: 'recommended', note: '0,75 % / 1,1 % Pauschal' },
  { id: 'flotte', name: 'Flottenversicherung', tier: 'recommended', note: 'Ab 3 Fahrzeugen' },
  { id: 'recht', name: 'Rechtsschutz Gewerbe Smart/Best', tier: 'recommended', note: 'Arbeitsrecht · Straf' },
  { id: 'bav', name: 'bAV (Top-up zu SOKA-BAU)', tier: 'optional', note: '§ 100 EStG Förderbetrag' },
  { id: 'bkv', name: 'bKV Budget', tier: 'optional', note: 'Listenpreise DKV' },
  { id: 'cyber', name: 'Cyber-Versicherung', tier: 'optional', note: 'Vollversion für ~200 MA' },
  { id: 'gebaeude', name: 'Gewerbliche Gebäudeversicherung', tier: 'optional', note: 'Nur bei Eigentum' },
];

export const HOTSPOTS = [
  { id: 'mensch', label: 'Mensch', x: -2.2, y: 1.4, z: 0.4 },
  { id: 'baustelle', label: 'Baustelle', x: 0.6, y: 2.1, z: -1.2 },
  { id: 'maschinen', label: 'Maschinen', x: 2.8, y: 0.9, z: 0.2 },
  { id: 'betrieb', label: 'Betrieb / Büro', x: -3.4, y: 0.6, z: -0.8 },
  { id: 'recht', label: 'Recht', x: 1.4, y: 0.5, z: 1.6 },
  { id: 'liquiditaet', label: 'Liquidität', x: -0.8, y: 0.35, z: 1.8 },
  { id: 'zukunft', label: 'Zukunft', x: 3.6, y: 1.8, z: -0.6 },
];

export const slides = [
  {
    id: 'hero',
    section: 'hero',
    kicker: 'ERGO  ·  Bau Partner',
    title: 'Ihr Fundament.\nAbgesichert.',
    line: 'Ein interaktives Angebot für Ihr Bauunternehmen — Absicherung aus einer Hand für ~200 Mitarbeitende.',
    facts: [
      { v: '~200', k: 'Mitarbeitende' },
      { v: '7+', k: 'Kernbausteine' },
      { v: 'Hybrid', k: 'Preislogik' },
    ],
    photos: [
      { src: p('photos/ergo/hq.jpg'), w: 5.5, h: 3.25, x: 2.75, y: 0.55, z: -0.25, ry: -0.12 },
    ],
    cam: { x: -0.45, y: 0.32, z: 8.3, tx: 1.6, ty: 0.3, tz: 0 },
    trail: false,
    site: 'wide',
  },
  {
    id: 'lage',
    section: 'lage',
    kicker: '01  ·  Ausgangslage',
    title: 'Was wir\nmitnehmen.',
    line: 'Platzhalter für die Risikoaufnahme — bitte mit Ihren Zahlen ersetzen.',
    facts: [
      { v: '~200', k: 'MA (Zielgröße)' },
      { v: 'Baustellen', k: 'Mehrere Objekte' },
      { v: 'Fuhrpark', k: 'LKWs · Transporter' },
      { v: 'Geräte', k: 'Bagger · Krane' },
      { v: 'Subs', k: 'Nachunternehmer' },
      { v: 'Bürgschaften', k: 'Banklinien entlasten' },
    ],
    cards: [
      { label: 'Discovery', sub: 'Zahlen folgen nach Risikoaufnahme.', kicker: 'Offen', x: 3.35, y: 0.35, z: 0.55, ry: -0.08 },
    ],
    cam: { x: -0.35, y: 0.3, z: 8.2, tx: 2.0, ty: 0.3, tz: 0 },
    trail: true,
    site: 'yard',
  },
  {
    id: 'risiko',
    section: 'risiko',
    kicker: '02  ·  Risiko-Landkarte',
    title: 'Sieben\nHotspots.',
    line: 'Mensch · Baustelle · Maschinen · Betrieb · Recht · Liquidität · Zukunft — klicken Sie die Marker in der Szene.',
    facts: [
      { v: '7', k: 'Risikofelder' },
      { v: '1', k: 'Partner' },
    ],
    hotspots: true,
    cam: { x: 0.2, y: 2.4, z: 11.5, tx: 0.4, ty: 1.0, tz: -0.4 },
    trail: true,
    site: 'map',
  },
  {
    id: 'haftung',
    section: 'haftung',
    kicker: '03  ·  Haftung',
    title: 'Betriebs-\nHaftpflicht.',
    line: 'Bauhauptgewerbe-Bedingungswerk: Tätigkeitsschäden, Subunternehmer, Abbruch ohne Radiusklausel, Umwelt, Asbest-Risiko.',
    facts: [
      { v: 'Tätigkeit', k: 'Kundeneigentum' },
      { v: 'Subs', k: 'Beauftragungsrisiko' },
      { v: 'Umwelt', k: '+ Asbest' },
    ],
    cards: [
      { label: 'BAU-Wortlaut', sub: 'Eigene Bedingungen fürs Bauhauptgewerbe.', kicker: 'Kern', x: 2.95, y: 0.4, z: 0.45, ry: 0.08 },
      { label: 'Abwehr', sub: 'ERGO prüft, zahlt, wehrt ab.', kicker: 'Service', x: 5.85, y: 0.4, z: 0.45, ry: -0.1 },
    ],
    legal: true,
    cam: { x: -0.15, y: 0.35, z: 9.4, tx: 4.2, ty: 0.4, tz: 0 },
    trail: true,
    site: 'scaffold',
  },
  {
    id: 'bauwerk',
    section: 'bauwerk',
    kicker: '04  ·  Bauwerk',
    title: 'Bauleistungs-\nversicherung.',
    line: 'Schutz für Bauwerk, Materialien und Bauteile während der Errichtung. Montageversicherung wo relevant.',
    facts: [
      { v: 'bis €5 Mio.', k: 'Tarifgrenze Objekt' },
      { v: 'Unvorhergesehen', k: 'Sachschäden am Bau' },
      { v: 'Hinweis', k: 'ABU prüfen' },
    ],
    cards: [
      {
        label: 'Objekt / Rahmen',
        sub: 'Öffentliche Seite zielt auf Bauherren. Eine Jahrespolice für den Unternehmer (ABU) bedarf ggf. der Underwriting-Bestätigung.',
        kicker: 'Sorgfalt',
        x: 3.35,
        y: 0.35,
        z: 0.55,
        ry: -0.08,
      },
    ],
    legal: true,
    cam: { x: -0.3, y: 0.35, z: 8.1, tx: 2.0, ty: 0.35, tz: 0 },
    trail: false,
    site: 'building',
  },
  {
    id: 'maschinen',
    section: 'maschinen',
    kicker: '05  ·  Maschinen',
    title: 'Maschinen- und\nKaskoversicherung.',
    line: 'Für fahrbare Geräte: Bagger, Krane, Radlader, Telehandler — Bedienfehler, Diebstahl, Elementar.',
    facts: [
      { v: 'Neuwert', k: 'Totalverlust Jahr 1' },
      { v: 'Grob fahrlässig', k: 'Verzicht bis €25k' },
      { v: 'Untervers.', k: 'Verzicht bis €25k' },
    ],
    cards: [
      { label: 'Voll / Kasko', sub: 'Innere Betriebsschäden oder nur äußere Ereignisse.', kicker: 'Wahl', x: 2.95, y: 0.4, z: 0.45, ry: 0.08 },
      { label: 'GAP optional', sub: 'Leasing & Finanzierung.', kicker: 'Add-on', x: 5.85, y: 0.4, z: 0.45, ry: -0.1 },
    ],
    legal: true,
    cam: { x: -0.1, y: 0.38, z: 9.4, tx: 4.3, ty: 0.4, tz: 0 },
    trail: true,
    site: 'machine',
  },
  {
    id: 'inhalt',
    section: 'inhalt',
    kicker: '06  ·  Inhalt',
    title: 'Geschäfts-\ninhaltsversicherung.',
    line: 'Büro, Lager, Werkstatt — plus Bauhandwerker-Paket. Gebäude nur bei Eigentum. Cyber optional kurz erwähnt.',
    facts: [
      { v: 'NeuwertPlus', k: 'Wiederbeschaffung' },
      { v: 'Handwerker', k: 'Baustellen-Extras' },
      { v: 'Cyber', k: 'Optional Vollversion' },
    ],
    photos: [
      { src: p('photos/ergo/office.jpg'), w: 5.35, h: 3.0, x: 2.7, y: 0.6, z: -0.15, ry: -0.1 },
    ],
    legal: true,
    cam: { x: -0.35, y: 0.25, z: 7.7, tx: 1.7, ty: 0.35, tz: 0 },
    trail: false,
    site: 'yard',
  },
  {
    id: 'recht',
    section: 'recht',
    kicker: '07  ·  Recht',
    title: 'Rechtsschutz\nGewerbe.',
    line: 'Smart oder Best — unbegrenzte Versicherungssumme. Stark bei Arbeitsrecht, Verkehrsrecht und Spezial-Straf.',
    facts: [
      { v: 'Smart / Best', k: 'Linien' },
      { v: '∞', k: 'VS auch im Basis' },
      { v: 'Hinweis', k: 'Werkvertrag oft raus' },
    ],
    cards: [
      {
        label: 'Kern-Bauverträge',
        sub: 'Streit aus Werkvertrag / VOB ist typischerweise nicht automatisch gedeckt. Optional: Vertrags-RS prüfen.',
        kicker: 'Wichtig',
        x: 3.35,
        y: 0.35,
        z: 0.55,
        ry: -0.08,
      },
    ],
    legal: true,
    cam: { x: -0.3, y: 0.3, z: 8.1, tx: 2.0, ty: 0.3, tz: 0 },
    trail: true,
    site: 'scaffold',
  },
  {
    id: 'liquiditaet',
    section: 'liquiditaet',
    kicker: '08  ·  Liquidität',
    title: 'Kaution &\nFlotte.',
    line: 'Kautionsversicherung statt Bankbürgschaft — plus Flottenversicherung für den Fuhrpark.',
    facts: [
      { v: '0,75 %', k: 'Kompakt p.a.' },
      { v: '1,1 %', k: 'Plus p.a.' },
      { v: 'bis €1 Mio.', k: 'Pauschal-Linie' },
    ],
    cards: [
      { label: 'Kompakt', sub: 'Leistung + Gewährleistung. 0,75 % der Linie p.a.', kicker: 'Pauschal', x: 2.95, y: 0.4, z: 0.45, ry: 0.08 },
      { label: 'Plus', sub: 'inkl. Anzahlung bis 30 %. 1,1 % p.a.', kicker: 'Pauschal', x: 5.85, y: 0.4, z: 0.45, ry: -0.1 },
    ],
    legal: true,
    cam: { x: -0.1, y: 0.35, z: 9.4, tx: 4.2, ty: 0.4, tz: 0 },
    trail: false,
    site: 'wide',
  },
  {
    id: 'menschen',
    section: 'menschen',
    kicker: '09  ·  Menschen',
    title: 'Unfall · bKV · bAV.',
    line: 'Gruppen-Unfall als Ergänzung zur BG BAU. bKV Budget mit Listenpreisen. bAV als Top-up zur SOKA-BAU Tarifrente.',
    facts: [
      { v: '1 % vs 20 %', k: 'Invalidität vs. MdE' },
      { v: '24/7', k: 'auch Freizeit' },
      { v: 'SOKA', k: 'West 3,2 % / Ost 1,7 %' },
    ],
    chips: [
      { v: '€15,68', k: 'bKV €300 / MA / Mo.' },
      { v: '€25,97', k: 'bKV €600' },
      { v: '€33,84', k: 'bKV €900' },
      { v: '€40,21', k: 'bKV €1.200' },
      { v: '€240–960', k: '§100 AG-Beitrag / Jahr' },
      { v: '30 %', k: 'Steuerrückfluss max. €288' },
    ],
    cards: [
      {
        label: 'BG-Lücke',
        sub: 'BG BAU: Rente ab 20 % MdE, keine Freizeit. ERGO: ab 1 % Invalidität, weltweit.',
        kicker: 'Unfall',
        x: 2.95,
        y: 0.4,
        z: 0.45,
        ry: 0.06,
      },
      {
        label: 'bAV Top-up',
        sub: 'SOKA-BAU bleibt. ERGO ergänzt Angestellte, Poliere, Führung. Ab 2027 höhere §100-Deckel.',
        kicker: 'Vorsorge',
        x: 5.85,
        y: 0.4,
        z: 0.45,
        ry: -0.08,
      },
    ],
    legal: true,
    cam: { x: -0.05, y: 0.38, z: 9.5, tx: 4.3, ty: 0.4, tz: 0 },
    trail: true,
    site: 'yard',
  },
  {
    id: 'warum',
    section: 'warum',
    kicker: '10  ·  Warum ERGO',
    title: 'Fünf Gründe.',
    line: 'Was auf der Baustelle zählt, zählt auch in der Police.',
    facts: [
      { v: '01', k: 'Ein Partner, volles Baurisiko' },
      { v: '02', k: 'Deckung die sich verbessert' },
      { v: '03', k: 'Faire Regulierung vor Ort' },
      { v: '04', k: 'Liquidität via Kaution' },
      { v: '05', k: 'Munich Re + Tarife 2026' },
    ],
    photos: [
      { src: p('photos/ergo/sign.jpg'), w: 4.2, h: 4.2, x: 3.05, y: 0.35, z: 0.05, ry: -0.1 },
    ],
    cam: { x: -0.4, y: 0.25, z: 7.8, tx: 1.85, ty: 0.3, tz: 0 },
    trail: true,
    site: 'wide',
  },
  {
    id: 'beitrag',
    section: 'beitrag',
    kicker: '11  ·  Beitrag',
    title: 'Wie Ihr Beitrag\nentsteht.',
    line: 'Keine erfundenen Kernbeiträge. Nur Preistreiber und die wenigen öffentlichen Listenwerte.',
    chips: [
      { v: 'Lohnsumme', k: 'Treiber' },
      { v: 'Bauvolumen', k: 'Treiber' },
      { v: 'Gerätewerte', k: 'Treiber' },
      { v: 'Schadenverlauf', k: 'Treiber' },
      { v: 'Selbstbehalt', k: 'Treiber' },
      { v: '0,75 % / 1,1 %', k: 'Kaution Pauschal' },
      { v: 'bKV Listen', k: 'ab €15,68 / MA' },
      { v: '§100 EStG', k: '30 % Rückfluss' },
    ],
    cta: true,
    cam: { x: -0.3, y: 0.3, z: 8.5, tx: 1.2, ty: 0.25, tz: 0 },
    trail: false,
    site: 'map',
  },
  {
    id: 'paket',
    section: 'paket',
    kicker: '12  ·  Paket-Bausteine',
    title: 'Must · Empfohlen\n· Optional.',
    line: 'Bausteine wählen — ohne Euro-Beträge auf den Kernprodukten. Bindende Zahlen folgen im Angebots-PDF.',
    builder: true,
    cta: true,
    cam: { x: 0.1, y: 0.4, z: 9.2, tx: 1.0, ty: 0.3, tz: 0 },
    trail: true,
    site: 'wide',
  },
  {
    id: 'naechste',
    section: 'naechste',
    kicker: '13  ·  Nächste Schritte',
    title: 'Checkliste &\nZeitplan.',
    line: 'Daten für die Risikoaufnahme — dann individuelles Angebot in ca. 10 Werktagen.',
    checklist: [
      'Lohnsumme (gewerblich / angestellt)',
      'Umsatz & Bauvolumen (Jahresrahmen)',
      'Geräteliste mit Neuwert & Baujahr',
      'Fuhrpark (Anzahl, Typen, SF)',
      'Schadenverlauf 5 Jahre',
      'Bürgschaftsbedarf (Linie, Arten)',
      'Bestehende Policen / Ablösung',
    ],
    facts: [
      { v: '30 Min.', k: 'Risikoaufnahme' },
      { v: '~10 WT', k: 'Angebot' },
    ],
    cta: true,
    cam: { x: -0.35, y: 0.28, z: 8.4, tx: 1.5, ty: 0.25, tz: 0 },
    trail: false,
    site: 'yard',
  },
  {
    id: 'schluss',
    section: 'schluss',
    kicker: '14  ·  Abschluss',
    title: 'Sie bauen.\nWir absichern.',
    line: '',
    quote:
      'Auf Ihren Baustellen zählt, dass jedes Gewerk sitzt — bei Ihrer Absicherung sollte es genauso sein. ERGO deckt Ihr gesamtes Baurisiko aus einer Hand ab: von der Betriebs-Haftpflicht mit eigenem Bau-Bedingungswerk über Bauleistung und Maschinen bis zu Bürgschaften, Rechtsschutz und Vorsorge für Ihre Mitarbeitenden.',
    cite: 'Nächster Schritt: 30 Minuten Risikoaufnahme → individuelles Angebot',
    photos: [
      { src: p('photos/ergo/team.jpg'), w: 5.3, h: 3.5, x: 2.75, y: 0.4, z: 0.0, ry: -0.08 },
    ],
    cta: true,
    cam: { x: -0.35, y: 0.25, z: 7.8, tx: 1.7, ty: 0.3, tz: 0 },
    trail: true,
    site: 'building',
  },
];
